/**
 * Dev seed script — inserts realistic sample jobs for frontend development.
 * Usage: bun scripts/seed.ts
 */
import "dotenv/config";
import { hashUrl, upsertJobs } from "@/lib/dedup";
import type { NewJob } from "@/db/schema";

const SEED_JOBS: Omit<NewJob, "urlHash">[] = [
  // LinkedIn — Bengaluru
  {
    url: "https://linkedin.com/jobs/view/1001",
    title: "Senior Frontend Engineer",
    titleNormalized: "senior frontend engineer",
    company: "Razorpay",
    companyNormalized: "razorpay",
    source: "linkedin",
    locationRaw: "Bengaluru, Karnataka, India",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    workMode: "hybrid",
    jobType: "full_time",
    experienceLevel: "senior",
    salaryRaw: "₹30–50 LPA",
    salaryMin: 3000000,
    salaryMax: 5000000,
    skillsRaw: ["React", "TypeScript", "Next.js", "GraphQL", "CSS"],
    applyUrl: "https://razorpay.com/jobs/frontend-engineer",
    description: "Build world-class payment experiences used by millions of merchants and consumers across India. You'll own the frontend architecture for our core checkout flow.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 2 * 86_400_000),
  },
  {
    url: "https://linkedin.com/jobs/view/1002",
    title: "Backend Engineer – Platform",
    titleNormalized: "backend engineer platform",
    company: "PhonePe",
    companyNormalized: "phonepe",
    source: "linkedin",
    locationRaw: "Bengaluru, Karnataka, India",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    workMode: "onsite",
    jobType: "full_time",
    experienceLevel: "mid",
    salaryRaw: "₹18–28 LPA",
    salaryMin: 1800000,
    salaryMax: 2800000,
    skillsRaw: ["Go", "Kubernetes", "gRPC", "PostgreSQL", "Redis"],
    applyUrl: "https://phonepe.com/careers/backend",
    description: "Join our platform team building highly reliable distributed systems that process millions of UPI transactions daily. You'll work on critical infrastructure components.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 1 * 86_400_000),
  },
  {
    url: "https://linkedin.com/jobs/view/1003",
    title: "iOS Engineer",
    titleNormalized: "ios engineer",
    company: "Dream11",
    companyNormalized: "dream11",
    source: "linkedin",
    locationRaw: "Mumbai, Maharashtra, India (Remote)",
    city: "Mumbai",
    state: "Maharashtra",
    country: "IN",
    workMode: "remote",
    jobType: "full_time",
    experienceLevel: "mid",
    salaryRaw: "₹25–40 LPA",
    salaryMin: 2500000,
    salaryMax: 4000000,
    skillsRaw: ["Swift", "SwiftUI", "Combine", "XCTest", "CI/CD"],
    applyUrl: "https://dream11.com/careers/ios",
    description: "Build the fantasy sports experience for 200M+ users on iOS. You'll own key features of our app, write tests, and ship fast.",
    isRemote: true,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 8 * 3600_000),
  },
  {
    url: "https://linkedin.com/jobs/view/1004",
    title: "Product Designer",
    titleNormalized: "product designer",
    company: "Zepto",
    companyNormalized: "zepto",
    source: "linkedin",
    locationRaw: "Mumbai, Maharashtra, India",
    city: "Mumbai",
    state: "Maharashtra",
    country: "IN",
    workMode: "onsite",
    jobType: "full_time",
    experienceLevel: "mid",
    salaryRaw: "₹18–30 LPA",
    salaryMin: 1800000,
    salaryMax: 3000000,
    skillsRaw: ["Figma", "Prototyping", "Design Systems", "User Research", "Motion"],
    applyUrl: "https://zepto.com/careers/product-designer",
    description: "Design delightful 10-minute delivery experiences for grocery at scale. You'll own the end-to-end design for the consumer checkout and post-order experience.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 6 * 3600_000),
  },
  {
    url: "https://linkedin.com/jobs/view/1005",
    title: "Engineering Manager – Payments",
    titleNormalized: "engineering manager payments",
    company: "Ola",
    companyNormalized: "ola",
    source: "linkedin",
    locationRaw: "Bengaluru, Karnataka, India",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    workMode: "hybrid",
    jobType: "full_time",
    experienceLevel: "manager",
    salaryRaw: "₹50–80 LPA",
    salaryMin: 5000000,
    salaryMax: 8000000,
    skillsRaw: ["Leadership", "System Design", "Microservices", "Hiring", "Roadmap"],
    applyUrl: "https://ola.com/careers/em-payments",
    description: "Lead a team of 8–12 engineers building Ola's ride-hailing payment platform. Manage roadmap, hiring, and execution for a critical business function.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 3 * 86_400_000),
  },

  // Naukri — mixed cities
  {
    url: "https://naukri.com/job-listings/1001",
    title: "Full Stack Developer",
    titleNormalized: "full stack developer",
    company: "Zomato",
    companyNormalized: "zomato",
    source: "naukri",
    locationRaw: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    country: "IN",
    workMode: "hybrid",
    jobType: "full_time",
    experienceLevel: "mid",
    salaryRaw: "15-25 Lacs PA",
    salaryMin: 1500000,
    salaryMax: 2500000,
    skillsRaw: ["Node.js", "React", "MongoDB", "Docker", "AWS"],
    applyUrl: "https://naukri.com/job-listings/1001/apply",
    description: "Build the future of food delivery. Work on high-scale microservices that handle peak traffic of 2M+ orders per day.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 3 * 86_400_000),
  },
  {
    url: "https://naukri.com/job-listings/1002",
    title: "React Native Developer",
    titleNormalized: "react native developer",
    company: "Swiggy",
    companyNormalized: "swiggy",
    source: "naukri",
    locationRaw: "Bengaluru | Work From Home",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    workMode: "remote",
    jobType: "full_time",
    experienceLevel: "mid",
    salaryRaw: "20-32 Lacs PA",
    salaryMin: 2000000,
    salaryMax: 3200000,
    skillsRaw: ["React Native", "Redux", "TypeScript", "iOS", "Android"],
    applyUrl: "https://naukri.com/job-listings/1002/apply",
    description: "Power Swiggy mobile app used by 50M+ users. Own features end to end — from product spec to Play Store release.",
    isRemote: true,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 5 * 3600_000),
  },
  {
    url: "https://naukri.com/job-listings/1003",
    title: "Data Engineer",
    titleNormalized: "data engineer",
    company: "Flipkart",
    companyNormalized: "flipkart",
    source: "naukri",
    locationRaw: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    workMode: "hybrid",
    jobType: "full_time",
    experienceLevel: "senior",
    salaryRaw: "22-38 Lacs PA",
    salaryMin: 2200000,
    salaryMax: 3800000,
    skillsRaw: ["Spark", "Hive", "Kafka", "Scala", "Airflow"],
    applyUrl: "https://naukri.com/job-listings/1003/apply",
    description: "Build the data pipelines that power Flipkart's e-commerce analytics and personalization at petabyte scale.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 2 * 86_400_000),
  },
  {
    url: "https://naukri.com/job-listings/1004",
    title: "SDE II – Search & Discovery",
    titleNormalized: "sde ii search discovery",
    company: "Myntra",
    companyNormalized: "myntra",
    source: "naukri",
    locationRaw: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    workMode: "onsite",
    jobType: "full_time",
    experienceLevel: "mid",
    salaryRaw: "20-35 Lacs PA",
    salaryMin: 2000000,
    salaryMax: 3500000,
    skillsRaw: ["Java", "Elasticsearch", "Spring Boot", "Kafka", "Redis"],
    applyUrl: "https://myntra.com/careers/sde-ii",
    description: "Own Myntra's search ranking and product discovery systems used by 50M+ fashion shoppers every month.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 4 * 86_400_000),
  },
  {
    url: "https://naukri.com/job-listings/1005",
    title: "Android Engineer",
    titleNormalized: "android engineer",
    company: "CRED",
    companyNormalized: "cred",
    source: "naukri",
    locationRaw: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    workMode: "hybrid",
    jobType: "full_time",
    experienceLevel: "senior",
    salaryRaw: "30-50 Lacs PA",
    salaryMin: 3000000,
    salaryMax: 5000000,
    skillsRaw: ["Kotlin", "Jetpack Compose", "Coroutines", "Clean Architecture", "RxJava"],
    applyUrl: "https://cred.club/careers/android",
    description: "Craft premium Android experiences that delight CRED's credit card user base. Own core payment and rewards UI modules.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 1 * 86_400_000),
  },

  // Indeed — diverse roles
  {
    url: "https://indeed.com/viewjob?jk=1001",
    title: "DevOps Engineer",
    titleNormalized: "devops engineer",
    company: "upGrad",
    companyNormalized: "upgrad",
    source: "indeed",
    locationRaw: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    country: "IN",
    workMode: "hybrid",
    jobType: "full_time",
    experienceLevel: "senior",
    salaryRaw: "₹25–40 LPA",
    salaryMin: 2500000,
    salaryMax: 4000000,
    skillsRaw: ["Terraform", "AWS", "Kubernetes", "CI/CD", "Python"],
    applyUrl: "https://indeed.com/viewjob?jk=1001&apply=1",
    description: "Build and maintain cloud infrastructure for upGrad's EdTech platform serving 10M+ learners. Own IaC, deployments, and SRE practices.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 4 * 86_400_000),
  },
  {
    url: "https://indeed.com/viewjob?jk=1002",
    title: "Software Engineer – ML Platform",
    titleNormalized: "software engineer ml platform",
    company: "Meesho",
    companyNormalized: "meesho",
    source: "indeed",
    locationRaw: "Bengaluru, Karnataka (Remote OK)",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    workMode: "remote",
    jobType: "full_time",
    experienceLevel: "entry",
    salaryRaw: "₹12–20 LPA",
    salaryMin: 1200000,
    salaryMax: 2000000,
    skillsRaw: ["Python", "PyTorch", "Spark", "Airflow", "SQL"],
    applyUrl: "https://indeed.com/viewjob?jk=1002&apply=1",
    description: "Work on ML infrastructure powering product recommendations for 140M+ users. Build training pipelines and feature stores.",
    isRemote: true,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 1 * 86_400_000),
  },
  {
    url: "https://indeed.com/viewjob?jk=1003",
    title: "QA Engineer – Automation",
    titleNormalized: "qa engineer automation",
    company: "BrowserStack",
    companyNormalized: "browserstack",
    source: "indeed",
    locationRaw: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    country: "IN",
    workMode: "remote",
    jobType: "full_time",
    experienceLevel: "mid",
    salaryRaw: "₹14–22 LPA",
    salaryMin: 1400000,
    salaryMax: 2200000,
    skillsRaw: ["Selenium", "Cypress", "JavaScript", "CI/CD", "API Testing"],
    applyUrl: "https://browserstack.com/careers/qa-automation",
    description: "Own test automation for BrowserStack's developer-facing platform. Build frameworks, set standards, and mentor the team.",
    isRemote: true,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 2 * 86_400_000),
  },
  {
    url: "https://indeed.com/viewjob?jk=1004",
    title: "Security Engineer",
    titleNormalized: "security engineer",
    company: "Razorpay",
    companyNormalized: "razorpay",
    source: "indeed",
    locationRaw: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    workMode: "hybrid",
    jobType: "full_time",
    experienceLevel: "senior",
    salaryRaw: "₹28–45 LPA",
    salaryMin: 2800000,
    salaryMax: 4500000,
    skillsRaw: ["AppSec", "Penetration Testing", "OWASP", "Cloud Security", "Python"],
    applyUrl: "https://razorpay.com/careers/security-engineer",
    description: "Protect payments infrastructure handling ₹5T+ annually. Conduct security reviews, build detection pipelines, and run the bug bounty program.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 12 * 3600_000),
  },
  {
    url: "https://indeed.com/viewjob?jk=1005",
    title: "Technical Program Manager",
    titleNormalized: "technical program manager",
    company: "Walmart Global Tech",
    companyNormalized: "walmart global tech",
    source: "indeed",
    locationRaw: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    workMode: "hybrid",
    jobType: "full_time",
    experienceLevel: "senior",
    salaryRaw: "₹35–55 LPA",
    salaryMin: 3500000,
    salaryMax: 5500000,
    skillsRaw: ["Program Management", "Agile", "Jira", "Cross-functional", "OKRs"],
    applyUrl: "https://walmart.com/careers/tpm",
    description: "Drive large-scale engineering programs across Walmart's India tech hub. Own delivery, remove blockers, and align stakeholders across time zones.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 5 * 86_400_000),
  },

  // More variety
  {
    url: "https://linkedin.com/jobs/view/1006",
    title: "Staff Engineer – Infrastructure",
    titleNormalized: "staff engineer infrastructure",
    company: "Atlassian",
    companyNormalized: "atlassian",
    source: "linkedin",
    locationRaw: "Bengaluru, Karnataka, India (Remote OK)",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    workMode: "remote",
    jobType: "full_time",
    experienceLevel: "lead",
    salaryRaw: "₹60–90 LPA",
    salaryMin: 6000000,
    salaryMax: 9000000,
    skillsRaw: ["Distributed Systems", "AWS", "Java", "Architecture", "Mentoring"],
    applyUrl: "https://atlassian.com/company/careers/staff-engineer",
    description: "Shape the infrastructure that powers Jira, Confluence, and Bitbucket for millions of developers. Lead technically, influence the roadmap, and mentor senior engineers.",
    isRemote: true,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 3 * 3600_000),
  },
  {
    url: "https://naukri.com/job-listings/1006",
    title: "Frontend Developer – React",
    titleNormalized: "frontend developer react",
    company: "Freshworks",
    companyNormalized: "freshworks",
    source: "naukri",
    locationRaw: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "IN",
    workMode: "hybrid",
    jobType: "full_time",
    experienceLevel: "mid",
    salaryRaw: "16-24 Lacs PA",
    salaryMin: 1600000,
    salaryMax: 2400000,
    skillsRaw: ["React", "Redux", "JavaScript", "CSS", "Webpack"],
    applyUrl: "https://freshworks.com/jobs/frontend",
    description: "Build the UI for Freshdesk, Freshsales, and Freshservice — SaaS products used by 68,000+ businesses worldwide.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 7 * 3600_000),
  },
  {
    url: "https://indeed.com/viewjob?jk=1006",
    title: "Cloud Architect",
    titleNormalized: "cloud architect",
    company: "Infosys",
    companyNormalized: "infosys",
    source: "indeed",
    locationRaw: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    country: "IN",
    workMode: "hybrid",
    jobType: "full_time",
    experienceLevel: "director",
    salaryRaw: "₹45–70 LPA",
    salaryMin: 4500000,
    salaryMax: 7000000,
    skillsRaw: ["AWS", "Azure", "GCP", "Solution Architecture", "Migration"],
    applyUrl: "https://infosys.com/careers/cloud-architect",
    description: "Lead cloud transformation engagements for Fortune 500 clients. Design multi-cloud architectures, own technical pre-sales, and mentor architects.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 6 * 86_400_000),
  },
  {
    url: "https://linkedin.com/jobs/view/1007",
    title: "Founding Engineer",
    titleNormalized: "founding engineer",
    company: "Setu",
    companyNormalized: "setu",
    source: "linkedin",
    locationRaw: "Bengaluru, Karnataka, India",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    workMode: "onsite",
    jobType: "full_time",
    experienceLevel: "senior",
    salaryRaw: "₹35–60 LPA + equity",
    salaryMin: 3500000,
    salaryMax: 6000000,
    skillsRaw: ["Python", "Django", "PostgreSQL", "AWS", "Fintech APIs"],
    applyUrl: "https://setu.co/careers/founding-engineer",
    description: "Be among the first 10 engineers at Setu, building India's API infrastructure for financial services. Own architecture, work directly with founders.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 4 * 3600_000),
  },
  {
    url: "https://naukri.com/job-listings/1007",
    title: "Backend Developer – Node.js",
    titleNormalized: "backend developer nodejs",
    company: "Paytm",
    companyNormalized: "paytm",
    source: "naukri",
    locationRaw: "Noida, Uttar Pradesh",
    city: "Noida",
    state: "Uttar Pradesh",
    country: "IN",
    workMode: "onsite",
    jobType: "full_time",
    experienceLevel: "entry",
    salaryRaw: "8-14 Lacs PA",
    salaryMin: 800000,
    salaryMax: 1400000,
    skillsRaw: ["Node.js", "Express", "MySQL", "Redis", "REST APIs"],
    applyUrl: "https://paytm.com/careers/backend-nodejs",
    description: "Join Paytm's backend team building high-volume transaction APIs. Good opportunity for engineers 1–3 years out of college.",
    isRemote: false,
    isActive: true,
    isDeleted: false,
    postedAt: new Date(Date.now() - 9 * 3600_000),
  },
];

async function main() {
  console.log(`Seeding ${SEED_JOBS.length} jobs...`);

  const jobs = SEED_JOBS.map((job) => ({
    ...job,
    urlHash: hashUrl(job.url),
  }));

  const { inserted, updated } = await upsertJobs(jobs);
  console.log(`Done — inserted: ${inserted}, updated: ${updated}`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
